version: "3.8"

services:
  api_usuarios:
    container_name: backend_usuarios
    build: .
    ports:
      - 3001:3001
    environment:
      PORT: 3001
    env_file: .env
    volumes:
      - ./:/code
      - node_modules:/code/node_modules
    networks:
      - backend_usuarios
    depends_on:
      - db_usuarios

  db_servidores:
    container_name: backend_usuarios
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file: .env
    volumes:
      - ./src/database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - ./src/database:/var/lib/postgresql/database
    networks:
      - backend_usuarios

volumes:
  node_modules:
  database:
    driver: local

networks:
  backend_usuarios:
