"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const UsuarioController_1 = require("../controllers/UsuarioController");
const functionsJWT_1 = require("../utils/functionsJWT");
const router = (0, express_1.Router)();
exports.router = router;
const usuarioController = new UsuarioController_1.UsuarioController();
router.post('/signup', usuarioController.create);
router.post('/login', usuarioController.login);
router.post('/recover-password', usuarioController.recoverPassword);
router.get('/usuarios', functionsJWT_1.verifyJWT, usuarioController.all);
router.get('/usuarios/:id', functionsJWT_1.verifyJWT, usuarioController.one);
router.put('/usuarios/:id', functionsJWT_1.verifyJWT, usuarioController.update);
router.put('/change-password/:id', functionsJWT_1.verifyJWT, usuarioController.changePassword);
router.delete('/usuarios/:id', functionsJWT_1.verifyJWT, usuarioController.remove);
router.patch('/usuarios/:id', functionsJWT_1.verifyJWT, usuarioController.restore);
